version: '3.5'

services:

  postgres-main: {}

  postgres-mp:
    volumes:
      - ./init-mp.sql:/docker-entrypoint-initdb.d/init-mp.sql

  object-store-main: {}

  object-store-mp:
    image: ghcr.io/provenance-io/object-store:0.6.4
    container_name: object-store-mp
    networks:
      - p8e
    environment:
      - OS_URL=0.0.0.0
      - OS_PORT=8080
      - DB_CONNECTION_POOL_SIZE=3
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASS=password1
      - DB_PASSWORD=password1
      - DB_PORT=5432
      - DB_NAME=object-store-mp
      - DB_SCHEMA=public
      - URI_HOST=localhost:8080
      - STORAGE_TYPE=file_system
      - STORAGE_BASE_PATH=/mnt/data
      - RUST_LOG=warn,object_store=debug
      - TRACE_HEADER=x-trace-header
      - LOGGING_THRESHOLD_SECONDS=1
    ports:
      - 5001:8080
    volumes:
      - mp_object_store:/mnt/data
